CC	=  cc
CFLAGS	=  -I .
CFLAGS	+= -W -Wall -Wextra -Werror -Wfloat-equal
CFLAGS	+= -Wundef -Wpointer-arith -Wcast-align -Wshadow
CFLAGS	+= -Wstrict-overflow=5 -Wwrite-strings -Waggregate-return
CFLAGS	+= -Wswitch-enum -Wunreachable-code -Winit-self
CFLAGS	+= -Wno-unused-parameter -pedantic -O3
LDFLAGS	=

BASE_SOURCES    = main.c
SOURCES		= $(BASE_SOURCES) client.c buffer.c structures.c vector.c handlers.c
OBJS		= $(SOURCES:.c=.o)
EXECUTABLE	= shell

all: test

build: $(EXECUTABLE)

$(EXECUTABLE): $(OBJS)
	$(CC) $(LDFLAGS) $(OBJS) -o $@

.c.o:
	$(CC) $(CFLAGS) -c $< -o $@

test: build
	python checker.py -e ./$(EXECUTABLE) --max 25

clean:
	rm -rf $(EXECUTABLE) $(OBJS)

.PHONY: clean
